name: Security Vulnerability
description: Report a security vulnerability (private disclosure)
title: "[SECURITY] "
labels: ["security", "critical"]
body:
  - type: markdown
    attributes:
      value: |
        # 🔒 Security Vulnerability Report
        
        **⚠️ IMPORTANT**: For security vulnerabilities, please follow responsible disclosure practices:
        
        1. **DO NOT** create a public issue for security vulnerabilities
        2. **Email directly** to: yashabalam707@gmail.com
        3. **Include** all details from this template in your email
        4. **Wait** for acknowledgment before public disclosure
        
        This template is for reference only. Please use email for actual security reports.

  - type: textarea
    id: vulnerability-description
    attributes:
      label: Vulnerability Description
      description: Provide a clear description of the security vulnerability
      placeholder: |
        Describe the security issue:
        - What type of vulnerability is it?
        - What component is affected?
        - What is the potential impact?
    validations:
      required: true

  - type: dropdown
    id: vulnerability-type
    attributes:
      label: Vulnerability Type
      description: What type of security vulnerability is this?
      options:
        - Authentication/Authorization bypass
        - SQL Injection
        - Cross-Site Scripting (XSS)
        - Command Injection
        - Path Traversal
        - Information Disclosure
        - Denial of Service
        - Cryptographic Issue
        - Buffer Overflow
        - Privilege Escalation
        - Other
    validations:
      required: true

  - type: dropdown
    id: severity-level
    attributes:
      label: Severity Level
      description: How severe is this vulnerability?
      options:
        - Critical - Immediate threat, full system compromise
        - High - Significant security impact
        - Medium - Moderate security impact
        - Low - Minor security concern
    validations:
      required: true

  - type: textarea
    id: affected-components
    attributes:
      label: Affected Components
      description: Which parts of LEWIS are affected?
      placeholder: |
        List affected components:
        - Specific modules/files
        - Versions affected
        - Platforms affected
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the vulnerability
      placeholder: |
        Provide step-by-step reproduction:
        1. Setup environment...
        2. Execute command...
        3. Observe vulnerability...
    validations:
      required: true

  - type: textarea
    id: proof-of-concept
    attributes:
      label: Proof of Concept
      description: Provide a proof of concept (sanitized if necessary)
      render: shell
      placeholder: |
        Include PoC code or commands (remove sensitive data):
        
        # Example command or code here

  - type: textarea
    id: impact-assessment
    attributes:
      label: Impact Assessment
      description: Describe the potential impact of this vulnerability
      placeholder: |
        Potential impacts:
        - What data could be exposed?
        - What systems could be compromised?
        - What privileges could be escalated?
        - What services could be disrupted?
    validations:
      required: true

  - type: textarea
    id: mitigation-suggestions
    attributes:
      label: Suggested Mitigation
      description: Any suggestions for fixing or mitigating this vulnerability
      placeholder: |
        Suggestions for mitigation:
        - Code changes needed
        - Configuration updates
        - Workarounds available
        - References to security best practices

  - type: input
    id: discovery-method
    attributes:
      label: Discovery Method
      description: How was this vulnerability discovered?
      placeholder: "e.g., Manual testing, automated scanning, code review"

  - type: textarea
    id: environment-details
    attributes:
      label: Environment Details
      description: Details about the environment where this was discovered
      placeholder: |
        Environment information:
        - LEWIS version:
        - Operating System:
        - Python version:
        - Installation method:
        - Any other relevant details...

  - type: checkboxes
    id: disclosure-agreement
    attributes:
      label: Responsible Disclosure Agreement
      description: Please confirm your agreement to responsible disclosure
      options:
        - label: I agree to follow responsible disclosure practices
          required: true
        - label: I will not publicly disclose this vulnerability until it is fixed
          required: true
        - label: I will send this report privately to yashabalam707@gmail.com
          required: true

  - type: markdown
    attributes:
      value: |
        ---
        
        ## 📧 Next Steps
        
        1. **Email this report** to: yashabalam707@gmail.com
        2. **Include "LEWIS Security Vulnerability"** in the subject line
        3. **Wait for acknowledgment** (we aim to respond within 24 hours)
        4. **Coordinate disclosure** timeline if vulnerability is confirmed
        
        ## 🏆 Recognition
        
        Security researchers who responsibly disclose vulnerabilities will be:
        - Credited in security advisories (if desired)
        - Added to our security hall of fame
        - Eligible for bug bounty rewards (when program launches)
        
        Thank you for helping keep LEWIS secure! 🛡️
