apiVersion: v1
kind: ConfigMap
metadata:
  name: lewis-config
  namespace: lewis-system
  labels:
    app: lewis
    component: config
data:
  config.yaml: |
    core:
      debug: false
      development_mode: false
      log_level: INFO
      secret_key: ${LEWIS_SECRET_KEY}
      
    security:
      enable_csrf: true
      session_timeout: 1800
      rate_limiting: true
      max_requests_per_minute: 100
      
    database:
      type: postgresql
      host: lewis-postgresql
      port: 5432
      name: lewis_production
      ssl_mode: require
      
    redis:
      host: lewis-redis
      port: 6379
      password: ${REDIS_PASSWORD}
      
    interfaces:
      web:
        host: 0.0.0.0
        port: 8080
        ssl_enabled: true
        
    ai:
      models_path: /app/models
      temperature: 0.7
      max_tokens: 2048
      
    tools:
      timeout: 300
      parallel_execution: true
      max_concurrent: 10
      
    monitoring:
      prometheus:
        enabled: true
        port: 9090
      grafana:
        enabled: true
        port: 3000
---
apiVersion: v1
kind: Secret
metadata:
  name: lewis-secrets
  namespace: lewis-system
  labels:
    app: lewis
    component: secrets
type: Opaque
data:
  # Base64 encoded values - replace with actual secrets
  LEWIS_SECRET_KEY: bGV3aXMtc2VjcmV0LWtleS1jaGFuZ2UtdGhpcw==
  DATABASE_PASSWORD: cG9zdGdyZXNxbC1wYXNzd29yZA==
  REDIS_PASSWORD: cmVkaXMtcGFzc3dvcmQ=
  JWT_SECRET: and0LXNlY3JldC1rZXk=
  API_KEY: YXBpLWtleS1zZWNyZXQ=
