# LEWIS AI Configuration File
# This file contains all the settings and preferences for LEWIS (Linux Environment Working Intelligence System)

# General application settings
app_name: "LEWIS"  # Name of the application
version: "1.0"  # Current version of the application
default_theme: "cyberpunk"  # Theme for the user interface, set to "cyberpunk" for a futuristic look

# Voice and AI Engine Settings
voice_enabled: true  # Enable/Disable voice functionality
ai_engine: "gpt-neo"  # AI engine to be used for natural language processing (GPT-Neo for NLP)

# Logging settings for debugging and error tracking
log_level: "debug"  # Set the level of logging, options: "debug", "info", "warn", "error"
# A 'debug' level will give the most detailed logs for troubleshooting

# Web application settings
web_port: 5000  # The port on which the LEWIS web application will run (e.g., 5000 is a common choice)

# Database configuration
database_path: "./database/lewis.db"  # Path to the SQLite database used for storing memory, logs, etc.
# If using a different database like MySQL or PostgreSQL, update this to reflect the connection string
